/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'core.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./core.android-arm64.node')
          } else {
            nativeBinding = require('@d3motap3/core-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'core.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./core.android-arm-eabi.node')
          } else {
            nativeBinding = require('@d3motap3/core-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'core.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./core.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@d3motap3/core-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'core.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./core.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@d3motap3/core-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'core.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./core.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@d3motap3/core-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'core.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./core.darwin-universal.node')
      } else {
        nativeBinding = require('@d3motap3/core-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'core.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./core.darwin-x64.node')
          } else {
            nativeBinding = require('@d3motap3/core-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'core.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./core.darwin-arm64.node')
          } else {
            nativeBinding = require('@d3motap3/core-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'core.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./core.freebsd-x64.node')
      } else {
        nativeBinding = require('@d3motap3/core-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'core.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./core.linux-x64-musl.node')
            } else {
              nativeBinding = require('@d3motap3/core-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'core.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./core.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@d3motap3/core-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'core.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./core.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@d3motap3/core-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'core.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./core.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@d3motap3/core-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'core.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./core.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@d3motap3/core-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'core.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./core.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@d3motap3/core-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'core.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./core.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@d3motap3/core-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'core.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./core.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@d3motap3/core-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'core.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./core.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@d3motap3/core-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { hello, add, listDisplays, startCapture, stopCapture, getLatestFrame, getFrameCount, isCapturing, ffmpegVersion, isFfmpegAvailable, startRecording, stopRecording, getRecordingElapsedMs, isRecording, addSource, removeSource, listSources, listWindows, listWebcams, setLayout, getPreviewFrame, listAudioInputDevices, startRecordingV2, stopRecordingV2, getRecordingV2ElapsedMs, isRecordingV2, listAndroidDevices, isAdbAvailable, listIosDevices, terminalWriteInput, terminalResize, scriptRun, scriptCancel, scriptStatus, aiStartNarration, aiStartScriptGen, aiStatus, aiCancel, aiReset, setCaption, clearCaption, editorProbe, editorThumbnails, editorExport, editorExportStatus, editorProbeBundle, punchInStart, punchInStop, isPunchInActive } = nativeBinding

module.exports.hello = hello
module.exports.add = add
module.exports.listDisplays = listDisplays
module.exports.startCapture = startCapture
module.exports.stopCapture = stopCapture
module.exports.getLatestFrame = getLatestFrame
module.exports.getFrameCount = getFrameCount
module.exports.isCapturing = isCapturing
module.exports.ffmpegVersion = ffmpegVersion
module.exports.isFfmpegAvailable = isFfmpegAvailable
module.exports.startRecording = startRecording
module.exports.stopRecording = stopRecording
module.exports.getRecordingElapsedMs = getRecordingElapsedMs
module.exports.isRecording = isRecording
module.exports.addSource = addSource
module.exports.removeSource = removeSource
module.exports.listSources = listSources
module.exports.listWindows = listWindows
module.exports.listWebcams = listWebcams
module.exports.setLayout = setLayout
module.exports.getPreviewFrame = getPreviewFrame
module.exports.listAudioInputDevices = listAudioInputDevices
module.exports.startRecordingV2 = startRecordingV2
module.exports.stopRecordingV2 = stopRecordingV2
module.exports.getRecordingV2ElapsedMs = getRecordingV2ElapsedMs
module.exports.isRecordingV2 = isRecordingV2
module.exports.listAndroidDevices = listAndroidDevices
module.exports.isAdbAvailable = isAdbAvailable
module.exports.listIosDevices = listIosDevices
module.exports.terminalWriteInput = terminalWriteInput
module.exports.terminalResize = terminalResize
module.exports.scriptRun = scriptRun
module.exports.scriptCancel = scriptCancel
module.exports.scriptStatus = scriptStatus
module.exports.aiStartNarration = aiStartNarration
module.exports.aiStartScriptGen = aiStartScriptGen
module.exports.aiStatus = aiStatus
module.exports.aiCancel = aiCancel
module.exports.aiReset = aiReset
module.exports.setCaption = setCaption
module.exports.clearCaption = clearCaption
module.exports.editorProbe = editorProbe
module.exports.editorThumbnails = editorThumbnails
module.exports.editorExport = editorExport
module.exports.editorExportStatus = editorExportStatus
module.exports.editorProbeBundle = editorProbeBundle
module.exports.punchInStart = punchInStart
module.exports.punchInStop = punchInStop
module.exports.isPunchInActive = isPunchInActive
