/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hello(): string
export declare function add(a: number, b: number): number
export interface DisplayInfo {
  id: number
  width: number
  height: number
}
export declare function listDisplays(): Array<DisplayInfo>
export declare function startCapture(displayIndex: number, width: number, height: number): void
export declare function stopCapture(): void
export declare function getLatestFrame(): Buffer | null
export declare function getFrameCount(): number
export declare function isCapturing(): boolean
export declare function ffmpegVersion(): string
export declare function isFfmpegAvailable(): boolean
export interface RecordingResultInfo {
  outputPath: string
  frameCount: number
  durationMs: number
  format: string
}
export declare function startRecording(displayIndex: number, width: number, height: number, fps: number, outputPath: string, format: string, quality: string): void
export declare function stopRecording(): RecordingResultInfo
export declare function getRecordingElapsedMs(): number
export declare function isRecording(): boolean
