/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hello(): string
export declare function add(a: number, b: number): number
export interface DisplayInfo {
  id: number
  width: number
  height: number
}
export declare function listDisplays(): Array<DisplayInfo>
export declare function startCapture(displayIndex: number, width: number, height: number): void
export declare function stopCapture(): void
export declare function getLatestFrame(): Buffer | null
export declare function getFrameCount(): number
export declare function isCapturing(): boolean
export declare function ffmpegVersion(): string
export declare function isFfmpegAvailable(): boolean
export interface RecordingResultInfo {
  outputPath: string
  frameCount: number
  durationMs: number
  format: string
}
export declare function startRecording(displayIndex: number, width: number, height: number, fps: number, outputPath: string, format: string, quality: string): void
export declare function stopRecording(): RecordingResultInfo
export declare function getRecordingElapsedMs(): number
export declare function isRecording(): boolean
export interface SourceInfoJs {
  id: number
  name: string
  width: number
  height: number
  isActive: boolean
}
/**
 * Add a capture source. `source_type` is "display", "window", or "webcam".
 * `config_json` is a JSON string with source-specific config.
 */
export declare function addSource(sourceType: string, configJson: string): number
export declare function removeSource(sourceId: number): void
export declare function listSources(): Array<SourceInfoJs>
export interface WindowInfoJs {
  windowId: number
  title: string
  appName: string
  isOnScreen: boolean
}
export declare function listWindows(): Array<WindowInfoJs>
export interface WebcamInfoJs {
  deviceIndex: number
  name: string
  description: string
}
export declare function listWebcams(): Array<WebcamInfoJs>
export declare function setLayout(layoutJson: string): void
export declare function getPreviewFrame(maxWidth: number, maxHeight: number): Buffer | null
export interface AudioDeviceInfoJs {
  id: string
  name: string
  isDefault: boolean
}
export declare function listAudioInputDevices(): Array<AudioDeviceInfoJs>
export declare function startRecordingV2(outputWidth: number, outputHeight: number, fps: number, outputPath: string, format: string, quality: string, captureSystemAudio: boolean, captureMicrophone: boolean, microphoneDeviceId?: string | undefined | null): void
export declare function stopRecordingV2(): RecordingResultInfo
export declare function getRecordingV2ElapsedMs(): number
export declare function isRecordingV2(): boolean
export interface AdbDeviceJs {
  serial: string
  model: string
  state: string
}
export declare function listAndroidDevices(): Array<AdbDeviceJs>
export declare function isAdbAvailable(): boolean
export interface IosDeviceJs {
  deviceId: string
  name: string
  model: string
}
export declare function listIosDevices(): Array<IosDeviceJs>
export declare function terminalWriteInput(sourceId: number, data: Buffer): void
export declare function terminalResize(sourceId: number, rows: number, cols: number): void
export declare function scriptRun(yamlPath: string, outputPath: string): void
export declare function scriptCancel(): void
export declare function scriptStatus(): string
export declare function aiStartNarration(description: string, apiKey: string): void
export declare function aiStartScriptGen(description: string, apiKey: string): void
export declare function aiStatus(): string
export declare function aiCancel(): void
export declare function aiReset(): void
export declare function setCaption(text: string, position: string): void
export declare function clearCaption(): void
export interface VideoMetadataJs {
  durationMs: number
  width: number
  height: number
  fps: number
  codec: string
}
export declare function editorProbe(path: string): VideoMetadataJs
export declare function editorThumbnails(path: string, count: number, width: number): Array<Buffer>
export declare function editorExport(projectJson: string, outputPath: string): void
export declare function editorExportStatus(): string
